### ISSUE TITLE
Menu item Config

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_pascal_cpp_format#1]
Если для пункта в инф файле прописать параметр menu=o, то пункт будет не в Плагинс а в options/ settings-plugins

**Comment by iRamSoft** [comment]
Я для этого и указал menu=o

**Comment by Alexey-T** [comment]
А в ридми ссылаешься на меню Плагинс

**Comment by iRamSoft** [comment]
Тьфу, сейчас поправлю
