### ISSUE TITLE
STD code

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_pascal_cpp_format#3]
не видел ли ты стандартный код форматеров в JS format, CSS format, Json format? Можно много реюзать

**Comment by iRamSoft** [comment]
Хочешь чтобы я переделал как в JS Format ?

**Comment by Alexey-T** [comment]
да, если мой форматтер учитывает больше ситуаций (например проверка числа кареток, проверка "прямое или обратное выделение", проверка vert selection, проверка что выдел идет до начала строки)

**Comment by Alexey-T** [comment]
WIki
```
How to make formatter plugin?

    Fork plugin CSS Format (or JS Format). It has most of code done. It has 3 commands done: Format, Config global, Config local.
    Replace/delete its CSS (JS) modules
    Change options filename, change loading of options
    Change contents of func do_format()
```

**Comment by iRamSoft** [comment]
Okey... 😔
Я же делал свой, в неведении, что есть некий JS Format.

**Comment by Alexey-T** [comment]
мой форматтер дает две кмд - Config global, Config local. локал- открывает файл кфг в папке текущего файла. тебе 2 кмд не нужны? тогда убереш кмд "конфиг локал" из inf. останется "глобал".

**Comment by Alexey-T** [comment]
это если ты вообще разберешся как прикрутить твой кфг файл к моему коду.

**Comment by Alexey-T** [comment]
Наверно- не надо переделывать.

**Comment by Alexey-T** [comment]
да- лучше не переделывать.

**Comment by iRamSoft** [comment]
Брать чужое и готовое не всегда хорошо. Лучше на свои грабли наступать. :smile:
